name: Check App Sanity
on:
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest Unit tests
        run: npm run unit-test

      - name: Report Success
        if: success()
        run: echo "Vitest units passed!"
        
      - name: Report Failure
        if: failure()
        run: echo "Vitest units failed."

  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Start Database
        run: docker compose -f compose.test.yml up -d

      - name: Run Integration tests
        run: npm run integration-test

      - name: Report Success
        if: success()
        run: echo "Integration tests passed!"
        
      - name: Report Failure
        if: failure()
        run: echo "Integration tests failed."

      - name: Stop Containers
        if: always()
        run: docker compose -f compose.test.yml down
  # TODO : Integrate deployment