name: Check App Sanity
on:
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest Unit tests
        run: npm run unit-test

      - name: Report Success
        if: success()
        run: echo "Vitest units passed!"
        
      - name: Report Failure
        if: failure()
        run: echo "Vitest units failed."

  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        # Created .env file 
        working-directory: .
        run: |
          cat <<EOF > .env
          POSTGRES_USER="user_admin"
          POSTGRES_PASSWORD="mypassword"
          POSTGRES_DB="chat_db"
          POSTGRES_HOST="127.0.0.1"
          POSTGRES_REG_USER="regular_user"
          POSTGRES_REG_PASSWORD="regular_user"
          SESSION_SECRET=JKLSFD8493UIF94085
          FULL_URL="http://localhost:3000"
          EMAIL_HOST="smtp.ethereal.email"
          EMAIL_PORT="587"
          EMAIL_SECURE="false"
          EMAIL_USER="test@test.com"
          EMAIL_PASSWORD="test123"
          LLAMA3_URL="http://localhost:11435"
          TINYLLAMA_URL="http://localhost:11434"
          GEMMA3_URL="http://localhost:11437"
          EOF

      - name: Start Database
        working-directory: ./app/backend/database/test
        # env:
        run: |
          export POSTGRES_USER=user_admin
          export POSTGRES_PASSWORD=mypassword
          export POSTGRES_DB=chat_db
          docker compose -f compose.test.yml up -d

      - name: Run Integration tests
        run: npm run integration-test

      - name: Report Success
        if: success()
        run: echo "Integration tests passed!"
        
      - name: Report Failure
        if: failure()
        run: echo "Integration tests failed."

      - name: Stop Containers
        if: always()
        working-directory: ./app/backend/database/test
        run: docker compose -f compose.test.yml down
  # TODO : Integrate deployment